### ISSUE TITLE
AttributeError: module 'zulip' has no attribute 'Client'

### ISSUE THREAD

**Issue by meetmangukiya** [zulip/errbot-backend-zulip#2]
I think `zulip` has to be imported

**Comment by derAnfaenger** [comment]
Interesting, did you get this error with an installed `zulip` package?

**Comment by meetmangukiya** [comment]
No, zulip wasn't installed when I got this error

**Comment by meetmangukiya** [comment]
But, it didn't give me `ImportError`

**Comment by derAnfaenger** [comment]
Ok, so in that case the code should throw some useful error message instead of this - as you said, it is probably the module naming that creates the import confusion here. Are you using Python 2? In that case, can you try adding a `from __future__ import absolute_import` as the top line?

**Comment by meetmangukiya** [comment]
No, I am using python 3

**Comment by derAnfaenger** [comment]
Hmm, I wonder why why it would still try to import `zulip` even though that seems to be a relative import (which need a special syntax in python3 afaik). Anyway, since we are really only using the `Client` class from the `zulip` package, we would be best off to just change the existing `import zulip` to `import zulip.Client`, and update the respective calls from `zulip.Client` to `Client`.

@meetmangukiya can you try doing this and see if it changes anything?

**Comment by meetmangukiya** [comment]
Fixed
